# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 23.227.204.194
  become: yes

  tasks:

- name: Call Roles
  hosts: 23.227.204.194
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
